package itmo.blps.entity;

public enum NotificationType {
    LISTING_PUBLISHED,
    PROMOTION_ACTIVATED,
    PROMOTION_PAYMENT_FAILED,
    ARCHIVATION_SOON,
    PUBLICATION_EXTENDED,
    NEW_INQUIRY,
    SHOWING_SCHEDULED,
    SHOWING_REJECTED,
    LISTING_CLOSED
}
